from groq import Groq
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from datetime import datetime
import os

import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

def generate_runbook_content(incident_description: str, rca_response: str) -> dict:
    prompt = f"""You are a senior network engineer. Based on the following incident and root cause analysis, generate a detailed runbook.

Incident: {incident_description}

Root Cause Analysis: {rca_response}

Generate a structured runbook with exactly these sections:
1. INCIDENT SUMMARY - brief description
2. AFFECTED COMPONENTS - list of devices and services
3. PRE-CHECKS - things to verify before starting
4. STEP BY STEP REMEDIATION - numbered steps with exact CLI commands
5. VERIFICATION STEPS - how to confirm the fix worked
6. ROLLBACK PLAN - what to do if fix makes things worse
7. PREVENTION - how to prevent this in future

Be specific with CLI commands. Format CLI commands with >>> prefix."""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
        max_tokens=2048
    )
    
    content = response.choices[0].message.content
    sections = {}
    current_section = None
    current_content = []
    
    for line in content.split("\n"):
        line = line.strip()
        if not line:
            continue
        if any(f"{i}." in line for i in range(1, 8)):
            if current_section:
                sections[current_section] = "\n".join(current_content).strip()
            current_section = line
            current_content = []
        else:
            current_content.append(line)
    
    if current_section:
        sections[current_section] = "\n".join(current_content).strip()
    
    return sections

def create_runbook_pdf(incident_id: str, incident_description: str, rca_response: str) -> str:
    sections = generate_runbook_content(incident_description, rca_response)
    
    filename = f"runbook_{incident_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join("data", filename)
    
    doc = SimpleDocTemplate(
        filepath,
        pagesize=letter,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch
    )
    
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Normal'],
        fontSize=22,
        fontName='Helvetica-Bold',
        textColor=colors.HexColor('#1a1a1a'),
        spaceAfter=6,
        alignment=TA_LEFT
    )
    
    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontSize=11,
        fontName='Helvetica',
        textColor=colors.HexColor('#888888'),
        spaceAfter=4,
        alignment=TA_LEFT
    )
    
    section_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Normal'],
        fontSize=13,
        fontName='Helvetica-Bold',
        textColor=colors.HexColor('#c96442'),
        spaceBefore=18,
        spaceAfter=8,
        alignment=TA_LEFT
    )
    
    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontSize=10,
        fontName='Helvetica',
        textColor=colors.HexColor('#333333'),
        spaceAfter=4,
        leading=16,
        alignment=TA_LEFT
    )
    
    code_style = ParagraphStyle(
        'Code',
        parent=styles['Normal'],
        fontSize=9,
        fontName='Courier',
        textColor=colors.HexColor('#c96442'),
        backColor=colors.HexColor('#f5f5f5'),
        spaceAfter=4,
        spaceBefore=4,
        leftIndent=12,
        leading=14
    )
    
    story = []
    
    story.append(Paragraph("NetFix AI", subtitle_style))
    story.append(Paragraph(f"Incident Runbook — {incident_id}", title_style))
    story.append(Spacer(1, 4))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Confidential — Internal Use Only", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#c96442'), spaceAfter=16))
    
    meta_data = [
        ["Incident ID", incident_id],
        ["Generated By", "NetFix AI — Automated Runbook Generator"],
        ["Date", datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
        ["Classification", "Internal — Network Operations"],
    ]
    
    meta_table = Table(meta_data, colWidths=[2*inch, 4.5*inch])
    meta_table.setStyle(TableStyle([
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('FONTNAME', (1,0), (1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('TEXTCOLOR', (0,0), (0,-1), colors.HexColor('#888888')),
        ('TEXTCOLOR', (1,0), (1,-1), colors.HexColor('#333333')),
        ('ROWBACKGROUNDS', (0,0), (-1,-1), [colors.HexColor('#f9f9f9'), colors.white]),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#eeeeee')),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING', (0,0), (-1,-1), 10),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 16))
    
    story.append(Paragraph("Incident Description", section_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#eeeeee'), spaceAfter=8))
    story.append(Paragraph(incident_description, body_style))
    
    for section_title, section_content in sections.items():
        story.append(Paragraph(section_title, section_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#eeeeee'), spaceAfter=8))
        
        for line in section_content.split("\n"):
            line = line.strip()
            if not line:
                continue
            if line.startswith(">>>"):
                story.append(Paragraph(line, code_style))
            elif line.startswith(("-", "•", "*")):
                story.append(Paragraph(f"&nbsp;&nbsp;• {line[1:].strip()}", body_style))
            elif line[0].isdigit() and "." in line[:3]:
                story.append(Paragraph(f"<b>{line}</b>", body_style))
            else:
                story.append(Paragraph(line, body_style))
        
        story.append(Spacer(1, 4))
    
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#eeeeee')))
    story.append(Spacer(1, 6))
    story.append(Paragraph("Generated by NetFix AI — Automated Network Troubleshooting Assistant", subtitle_style))
    story.append(Paragraph("This runbook was auto-generated. Always verify steps with a senior network engineer before execution.", subtitle_style))
    
    doc.build(story)
    return filepath